[2016-11-09 21:01:29] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:12] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:22] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:31] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:32] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:41] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:42] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:03:52] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:04:08] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
[2016-11-09 21:05:33] silex.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_login_check" as such route does not exist.") in "admin/login.twig" at line 48. (uncaught exception) at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php line 411 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist.\") in \"admin/login.twig\" at line 48. at /Users/rkarkut/www/silex/vendor/twig/twig/lib/Twig/Template.php:411, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"admin_login_check\" as such route does not exist. at /Users/rkarkut/www/silex/vendor/symfony/routing/Generator/UrlGenerator.php:130)"} []
